name: 'Setup V Build'
description: 'Setup a V environment by downloading and unpacking or building the V compiler to the PATH.'
author: prantlf

branding:
  icon: check-square
  color: blue

inputs:
  version:
    description: 'version specification (latest, weekly, master, version number or a commit hash)'
    default: weekly
  use-cache:
    description: 'set to `false` to ignore the cache and always download and install or build'
    default: 'true'
  force-build:
    description: 'set to `true` to build V from sources although the binary archive is available'
    default: 'false'
  install-dependencies:
    description: 'set to `false` to not install dependencies from `v.mod`'
    default: 'true'
  token:
    description: 'Authorization token to inspect releases and commits in the `vlang/v` repository. Either a GitHub personal access token or the GitHub workflow token.'
    default: ${{ github.token }}
    required: true

outputs:
  version:
    description: 'actually installed version of V'
  bin-path:
    description: 'the directory with the V compiler'
  v-bin-path:
    description: 'the path to the V compiler executable'
  used-cache:
    description: 'a boolean value to indicate if the cache was hit'
  was-built:
    description: 'a boolean value to indicate if V was built from sources'

runs:
  using: node16
  main: 'dist/index.js'
